// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MrRobot.Infrastructure.EntityFrameworkDataAccess;

namespace MrRobot.Infrastructure.EntityFrameworkDataAccess.Migrations
{
    [DbContext(typeof(MrRobotContext))]
    [Migration("20190316182127_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MrRobot.Core.Entities.Location", b =>
                {
                    b.Property<Guid>("RobotId");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.HasKey("RobotId", "X", "Y");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("MrRobot.Core.Entities.Robot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Robots");
                });
#pragma warning restore 612, 618
        }
    }
}
